language: objective-c
osx_image: xcode9.2
env:
  matrix:
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=11.2'
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.2'
    - SCHEME=MQTTClientmacOS DESTINATION='platform=macOS'
before_install:
  - gem install xcpretty
  - brew install mosquitto
before_script: ./brokers/mosquitto/start.sh
script: xcodebuild clean test -project MQTTClient/MQTTClient.xcodeproj -scheme $SCHEME -destination "$DESTINATION"
after_script: ./brokers/mosquitto/stop.sh
